version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genai
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/genai
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHROMA_PERSIST_DIR: /data/chroma
      CHROMA_COLLECTION: kb_collection
    volumes:
      - ./backend/chroma_db:/data/chroma
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://backend:8000"
      VITE_API_WS_URL: "ws://backend:8000"
    depends_on:
      - backend

volumes:
  pgdata:
